### ISSUE TITLE
Implementazioni RequestAsync 

### ISSUE THREAD

**Issue by davideciarmiello** [nicogis/FatturazioneElettronica_IPA#1]
Ciao. Complimenti per l'ottimo lavoro.
Volevo sapere se potevi implementare sui vari WS i metodi RequestAsync come ad esempio:

`        public new System.Threading.Tasks.Task<Ws01> RequestAsync()
        {
            this.AddParameters(new KeyValuePair<string, string>("CF", this.CF));
            return base.RequestAsync();
        }
`
Te lo chiedo perchè ho visto che nel metodo base.Request, viene usato 
`this.SendRequest(requestParameters).Result;`, quindi di base la gestione della chiamata web in modo asincrono c'è.

Se è un problema, posso anche implementarlo io e fare la pull request.

Grazie, Davide

**Comment by nicogis** [comment]
Si se lo puoi fare ti ringrazio
Domenico

Il giorno mar 15 giu 2021 alle 14:00 Davide Ciarmiello <
***@***.***> ha scritto:
